name: ci
on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest

    env:
      PROJECT_ID: wawyqknllvxhusqpvcgr
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.PRODUCTION_DB_PASSWORD }}

    steps:
      - uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1

      - run: supabase link --project-ref $PROJECT_ID
      - run: supabase db push
